name: Check for updates
on:
  schedule: # for scheduling to work this file must be in the default branch
    - cron: "0 0 * * 0" # 00:00 on every Sunday
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ master ] # list all branches to check

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: flathubbot
          GIT_COMMITTER_NAME: flathubbot
          GIT_AUTHOR_EMAIL: sysadmin@flathub.org
          GIT_COMMITTER_EMAIL: sysadmin@flathub.org
          EMAIL: sysadmin@flathub.org
          GITHUB_TOKEN: ${{ secrets.FLATHUBBOT_TOKEN }}
        with:
          # We don't want the default entrypoint, we want our own script
          entrypoint: ./update-checker.sh
