name: Build and publish Flatpak repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Setup environment
        shell: bash
        run: |
          echo "Setting up environment..."
          # Set up a user as the docker image comes with none
          cat <<EOF > /etc/passwd
          root:x:0:0:root:/root:/bin/bash
          EOF
          
          cat <<EOF > /etc/group
          root:x:0:
          EOF
          
          # Configure Git for Flatpak operations
          git config --global --add safe.directory /__w/flatpak-pieces-test/flatpak-pieces-test
          
          # Add Flathub repository for dependencies
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          
          # Clone shared-modules if needed
          if [ ! -d "shared-modules" ]; then
            git clone https://github.com/flathub/shared-modules
          fi

      - name: Fix icon issues
        env:
          APP_ID: com.pieces.os
        shell: bash
        run: |
          cd apps/${APP_ID}
          
          # Fix icon naming
          if [ -f "pieces_server.png" ]; then
            cp pieces_server.png ${APP_ID}.png
          
            # Update desktop file
            if [ -f "pieces-os.desktop" ]; then
              sed -i "s/Icon=pieces_server/Icon=${APP_ID}/g" pieces-os.desktop
            fi
          fi
          
          cd -

      - name: Build Pieces OS without signing
        env:
          APP_ID: com.pieces.os
        shell: bash
        run: |
          # Build without GPG signing
          flatpak-builder --verbose build --user --install-deps-from=flathub --disable-rofiles-fuse --disable-updates --force-clean --repo=repo apps/${APP_ID}/${APP_ID}.yml

      - name: Update repository without signing
        shell: bash
        run: |
          # Update repo without signin
          flatpak build-update-repo repo/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./repo
          force_orphan: true